name: 'Run Checks: Lint, Audit and Build'

on: [push]

jobs:
  build:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Run Prettier
      - name: Run Prettier
        run: npm run format:check

      # Run ESLint
      - name: Run eslint
        run: npm run lint

      - name: Audit dependencies
        run: npm audit

      - name: Check types
        run: npm run typecheck

      - name: Check for circular dependencies
        run: npx madge --circular . --extensions ts,js,jsx,tsx

      - name: Build with npm
        env:
          BASE_URL: '/openfga.dev/'
        run: npm run build

  fossa:
    name: Run FOSSA
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1

      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}

  snyk:
    name: Run Snyk
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # Checking to ensure markdown link is not broken
  markdown-link-check-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        file-extension	: '.md'
        use-quiet-mode  : 'yes'
        config-file: '.github/workflows/markdown.links.config.json'

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        file-extension	: '.mdx'
        use-quiet-mode  : 'yes'
        config-file: '.github/workflows/markdown.links.config.json'